language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - flake8
script:
  - coverage run -m pytest tests
after_success:
  - coveralls
notifications:
  email: false