language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - flake8
  - isort
script:
  - coverage run -m pytest
after_success:
  - coveralls
notifications:
  email: false